### ISSUE TITLE
CODAL build broken

### ISSUE THREAD

**Issue by pelikhan** [LabAixBidouille-STM32/codal-stm32-iot-node#9]
```
ASE -DTARGET_STM -DDEVICE_SERIAL_FC=1 -DDEVICE_PORTINOUT=1 -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DDEVICE_SPI=1 -DUSB_STM_HAL -DDEVICE_ERROR_RED=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_PWMOUT=1 -DDEVICE_PORTIN=1 -DARM_MATH_CM4 -DTARGET_STM32L475xG -DMBED_CONF_RTOS_PRESENT=1 -DMBED_CONF_PLATFORM_STDIO_BAUD_RATE=9600 -DMBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE=9600 -DMBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT=1 -DMBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES=0 -DUSB_STM_HAL -DUSBHOST_OTHER -MMD -MT libraries/codal-stm32-iot-node/CMakeFiles/codal-stm32-iot-node.dir/model/STM32IotNodeHumidity.cpp.obj -MF libraries\codal-stm32-iot-node\CMakeFiles\codal-stm32-iot-node.dir\model\STM32IotNodeHumidity.cpp.obj.d -o libraries/codal-stm32-iot-node/CMakeFiles/codal-stm32-iot-node.dir/model/STM32IotNodeHumidity.cpp.obj -c ../libraries/codal-stm32-iot-node/model/STM32IotNodeHumidity.cpp
In file included from ../libraries/codal-stm32-iot-node/model/STM32IotNode.h:45:0,
                 from ../libraries/codal-stm32-iot-node/model/STM32IotNodeHumidity.cpp:32:
../libraries/codal-stm32-iot-node/model/STM32IotNodeDistance.h:46:2: error: expected class-name before '{' token
  {
  ^
[6/123] Building CXX object libraries/codal-stm32-iot-node...les/codal-stm32-iot-node.dir/model/STM32IotNodeI2C.cpp.obj
ninja: build stopped: subcommand failed.
INTERNAL ERROR: Error: Exit code: 1 from cd built/codal; python build.py
    at ChildProcess.<anonymous> (C:\gh\pxt\built\nodeutil.js:66:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

jhalleux@PELI-YOGA MINGW64 /c/gh/pxt-stm32-iot-node (serial)
$

```

**Comment by nedseb** [comment]
It's probably the same issue with the filename case sensitivity.... I'll correct now
